# .travis.yml

language: "java"

sudo: false

jdk:
  - "oraclejdk8"
  - "openjdk8"
  - "oraclejdk9"
  - "openjdk9"

addons:
  apt:
    packages:
      - "oracle-java8-installer"
      - "ant-optional"

script:
  - "ant test"
