# .travis.yml

language: "java"

sudo: false

jdk:
  - "oraclejdk8"
  - "openjdk8"
  - "oraclejdk9"

addons:
  apt:
    packages:
      - "oracle-java8-installer"
      - "ant-optional"

script:
  - |
    export JAVAC_SOURCE_VER=$(javac -version 2>&1 | sed -e 's/^javac \([0-9]\+\.[0-9]\+\).*$/\1/')
    export JAVAC_TARGET_VER=$JAVAC_SOURCE_VER

  - "ant test"
